# Generated by Django 2.1 on 2022-01-21 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landmark.Category'),
        ),
    ]
