# Generated by Django 3.2.3 on 2022-02-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0002_landmark_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='description',
            field=models.TextField(),
        ),
    ]
