# Generated by Django 3.2.3 on 2022-02-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0003_alter_landmark_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.TextField()),
                ('code', models.TextField()),
            ],
        ),
    ]
