# Generated by Django 3.0.8 on 2020-09-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=300)),
                ('nick', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=400)),
                ('gpa', models.FloatField(default=4.0)),
            ],
        ),
    ]
